### ISSUE TITLE
Game Initialization

### ISSUE THREAD

**Issue by matthaeusheer** [pokino-project/pokino#50]
# Game Initialization Procedure
- backend publishes on RabbitMQ topic
- first player clicks ready button -> REST call to backend (incl. player ID) -> listen on queue
- second player clicks ready button -> REST call to backend (incl. player ID) -> listen on queue
- backend publishes event {'playerIds': [23, 10]} on queue with two relevant ID's of players -> initializes game state logic
- two players switch into game view
- requests according to game state machine

## Backend RabbitMQ implementation
https://kennay-kermani.medium.com/simple-pub-sub-implementation-with-spring-boot-docker-and-rabbitmq-4ed7461de239

## Frontend RabbitMQ implementation
...

**Comment by Leo-Rutschmann** [comment]
description should be adjusted to WebSocket rather than RabbitMQ I guess

**Comment by Leo-Rutschmann** [comment]
Done via WebSockets, see e.g. #82, #110
